export const APP_NAME = '8BitFriends'
export const LOGIN_BUTTON = 'Login'
export const SIGNUP_BUTTON = 'Sign up'
export const PLACEHOLDER = 'Search users by username'
export const EMPTY_LIST_TITLE = 'No Results Found'
export const DISCOVER_EMPTY_LIST_SUBTITLE = 'Please try again'
export const FAVORITE_EMPTY_LIST_SUBTITLE = 'Start adding favorites from discover tab'
