# codegen.yml
schema: 
    - https://api.github.com/graphql
       headers:
          Authorization: Bearer XXXXXXXXXX
overwrite: true
generates:
  ./fragmentTypes.json:
    plugins:
      - fragment-matcher
